<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\Chrono.Domain\Chrono.Domain.csproj" />
  <ProjectReference Include="..\Chrono.Application\Chrono.Application.csproj" />
  <ProjectReference Include="..\Chrono.Boundary\Chrono.Boundary.csproj" />
  <ProjectReference Include="..\Chrono.UI\Chrono.UI.csproj" />
</ItemGroup>
</Project>
