<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\Chrono.Application\Chrono.Application.csproj" />
</ItemGroup>
<ItemGroup>
    <Reference Include="ScriptHookVDotNet3">
      <HintPath>..\..\lib\ScriptHookVDotNet3.dll</HintPath>
    </Reference>
  </ItemGroup>
<ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
